import { useCallback, useEffect, useMemo, useState } from "react";
import { Loader2, RefreshCw, Sparkles } from "lucide-react";
import Markdown from "react-markdown";
import remarkGfm from "remark-gfm";
import {
  getDigest,
  getMyEntry,
  invokeGenerateDigest,
  todayLocalDate,
} from "@/lib/queries/standup";
import { useSession } from "@/hooks/use-session";
import { useWorkspace } from "@/hooks/use-workspace";
import type { AsyncStandup, DailyDigest } from "@/lib/types";
import { cn } from "@/lib/cn";

function formatTime(iso: string): string {
  return new Date(iso).toLocaleTimeString([], {
    hour: "numeric",
    minute: "2-digit",
  });
}

export function DigestCard() {
  const { session } = useSession();
  const { workspace } = useWorkspace();
  const userId = session?.user?.id ?? null;
  const workspaceId = workspace?.id ?? null;

  const localDate = useMemo(() => todayLocalDate(), []);

  const [loadingInitial, setLoadingInitial] = useState(true);
  const [digest, setDigest] = useState<DailyDigest | null>(null);
  const [myEntry, setMyEntry] = useState<AsyncStandup | null>(null);
  const [regenerating, setRegenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!workspaceId || !userId) return;
    let cancelled = false;
    setLoadingInitial(true);
    Promise.all([
      getDigest(workspaceId, localDate),
      getMyEntry(workspaceId, userId, localDate),
    ])
      .then(([d, m]) => {
        if (cancelled) return;
        setDigest(d);
        setMyEntry(m);
      })
      .catch(() => {
        // Soft-fail to empty state; the user can attempt regenerate.
      })
      .finally(() => {
        if (!cancelled) setLoadingInitial(false);
      });
    return () => {
      cancelled = true;
    };
  }, [workspaceId, userId, localDate]);

  const onRegenerate = useCallback(async () => {
    if (!workspaceId || regenerating) return;
    setRegenerating(true);
    setError(null);
    try {
      const next = await invokeGenerateDigest(workspaceId, localDate);
      setDigest(next);
    } catch (e) {
      setError("Couldn't regenerate. Try again in a sec.");
      // eslint-disable-next-line no-console
      console.error(e);
    } finally {
      setRegenerating(false);
    }
  }, [workspaceId, localDate, regenerating]);

  // loading-initial: skeleton
  if (loadingInitial) {
    return (
      <div
        role="region"
        aria-label="Team digest"
        className="rounded-lg border border-border bg-card/50 p-5"
      >
        <SkeletonRows />
      </div>
    );
  }

  // empty: no digest yet
  if (!digest) {
    return (
      <div
        role="region"
        aria-label="Team digest"
        className="rounded-lg border border-dashed border-border bg-card/50 p-8 text-center"
      >
        <p className="text-sm text-muted-foreground">
          No entries yet today. The digest will appear once your team starts
          submitting.
        </p>
      </div>
    );
  }

  // stale-hint: user's latest entry is newer than the digest
  const stale =
    myEntry !== null &&
    new Date(myEntry.updated_at).getTime() >
      new Date(digest.generated_at).getTime();

  return (
    <div className="space-y-3">
      {stale ? (
        <div
          role="status"
          className="flex items-center justify-between gap-3 rounded-md border border-amber-500/30 bg-amber-500/10 px-3 py-2 text-xs text-amber-200"
        >
          <span>
            Your latest entry isn't in the digest yet — regenerate to include
            it.
          </span>
          <button
            type="button"
            onClick={() => void onRegenerate()}
            disabled={regenerating}
            className="inline-flex items-center gap-1 rounded-md border border-amber-500/40 bg-amber-500/10 px-2 py-1 text-xs font-medium text-amber-100 hover:bg-amber-500/20 disabled:cursor-not-allowed disabled:opacity-50"
          >
            <RefreshCw
              className={cn("h-3 w-3", regenerating && "animate-spin")}
            />
            Regenerate
          </button>
        </div>
      ) : null}

      <div
        role="region"
        aria-label={`Team digest for ${localDate}`}
        className="rounded-lg border border-border bg-card/50 p-5"
      >
        <header className="mb-3 flex items-start justify-between gap-3">
          <span
            aria-label="This content was generated by AI"
            className="inline-flex items-center gap-1 rounded-md bg-primary/15 px-2 py-0.5 text-xs font-medium text-primary"
          >
            <Sparkles className="h-3 w-3" />
            AI-generated
          </span>
          <button
            type="button"
            onClick={() => void onRegenerate()}
            disabled={regenerating}
            className="inline-flex items-center gap-1 rounded-md border border-border bg-background px-2.5 py-1 text-xs font-medium hover:bg-muted disabled:cursor-not-allowed disabled:opacity-50"
          >
            {regenerating ? (
              <>
                <Loader2 className="h-3 w-3 animate-spin" />
                Generating…
              </>
            ) : (
              <>
                <RefreshCw className="h-3 w-3" />
                Regenerate
              </>
            )}
          </button>
        </header>

        <div className="relative">
          <div
            className={cn(
              "prose prose-invert prose-sm max-w-none",
              regenerating && "opacity-50"
            )}
          >
            <Markdown remarkPlugins={[remarkGfm]}>{digest.body_md}</Markdown>
          </div>
          {regenerating ? (
            <div className="mt-3 flex items-center gap-2 text-xs text-muted-foreground">
              <Loader2 className="h-3.5 w-3.5 animate-spin" />
              Generating…
            </div>
          ) : null}
        </div>

        <div className="mt-4 text-xs text-muted-foreground">
          Generated at {formatTime(digest.generated_at)} &middot; {digest.model}{" "}
          &middot; {digest.entry_count}{" "}
          {digest.entry_count === 1 ? "entry" : "entries"}
        </div>

        {error ? (
          <p className="mt-3 text-xs text-destructive">{error}</p>
        ) : null}
      </div>
    </div>
  );
}

function SkeletonRows() {
  return (
    <div className="space-y-3">
      <div className="h-3 w-2/3 animate-pulse rounded bg-muted/60" />
      <div className="h-3 w-5/6 animate-pulse rounded bg-muted/60" />
      <div className="h-3 w-1/2 animate-pulse rounded bg-muted/60" />
    </div>
  );
}
